services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD", "pg_isready", "-U", "postgres"]  
      interval: 30s  
      timeout: 10s  
      retries: 5  


  migrate:
    build:  
      context: .
      dockerfile: Dockerfile
      target: migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONNECTION_STRING: Host=postgres;Database=postgres;Username=postgres;Password=postgres;


  build:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: Host=postgres;Database=postgres;Username=postgres;Password=postgres;
    ports:
      - "8085:80"

volumes:
  pgdata: