name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build the Docker image
        id: build_image
        run: |
          docker build -t test/negar-backend:latest .
          # docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/negar-backend:latest . 
          
      - name: Bump version and push tag
        if: steps.build_image.outcome == 'success'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push the Docker image
      #   if: steps.tag_version.outputs.new_tag != ''
      #   run: |
      #     docker tag ${{ secrets.DOCKERHUB_USERNAME }}/negar-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/negar-backend:${{ steps.tag_version.outputs.new_tag }}
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/negar-backend:${{ steps.tag_version.outputs.new_tag }}