name: CI-Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build migration Docker image
        id: migration_image
        run: |
          docker build --target migrate -t ${{ vars.DOCKERHUB_USERNAME }}/negar-migration:latest . 

      - name: Build the Docker image
        id: build_image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:latest . 
          
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push migration Docker image
        run : |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/negar-migration:latest
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/negar-migration:latest ${{ vars.DOCKERHUB_USERNAME }}/negar-migration:${{ steps.tag_version.outputs.new_tag }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/negar-migration:${{ steps.tag_version.outputs.new_tag }}

      - name: Push the Docker image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:latest
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:latest ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:${{ steps.tag_version.outputs.new_tag }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:${{ steps.tag_version.outputs.new_tag }}