name: CI-Merge  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-22.04  

    permissions:  
      contents: write  

    steps:  
      - uses: actions/checkout@v4  
        with:  
          fetch-depth: '0'  

      - name: Log in to Docker Hub  
        uses: docker/login-action@v2  
        with:  
          username: ${{ vars.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASS }}  

      - name: Build the Docker image  
        id: build_image  
        run: |  
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:latest .  

      - name: Bump version and push tag  
        id: tag_version  
        uses: mathieudutour/github-tag-action@v6.2  
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Push the Docker image  
        run: |  
          docker push ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:latest  
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:latest ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:${{ steps.tag_version.outputs.new_tag }}  
          docker push ${{ vars.DOCKERHUB_USERNAME }}/negar-backend:${{ steps.tag_version.outputs.new_tag }}  

      - name: Install GitHub CLI and yq 
        run: |  
          sudo apt-get update
          sudo apt-get install -y gh
          sudo snap install yq

      - name: Clone Deployment Repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'Star-Academy'
          repository: 'Summer1403-Project-Group04-Deployment'

      - name: Update values.yaml for backend  
        run: |  
          echo "Updating values.yaml for backend..."  
          cd Summer1403-Project-Group04-Deployment 
          yq eval ".backend.tag = \"${{ steps.tag_version.outputs.new_tag }}\"" -i values.yaml  

          git config --local user.email "m.h.chah4@gmail.com"  
          git config --local user.name "muhuchah"  
          
          # Create a new branch for the changes  
          NEW_BRANCH="update-backend-tag-${{ steps.tag_version.outputs.new_tag }}"  
          git checkout -b $NEW_BRANCH  
          git add values.yaml  
          git commit -m "Update backend tag to ${{ steps.tag_version.outputs.new_tag }}"  

      - name: Push changes to new branch
        run: |
          cd Summer1403-Project-Group04-Deployment
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/Star-Academy/Summer1403-Project-Group04-Deployment.git
          git push --set-upstream origin $NEW_BRANCH

      - name: Create Pull Request  
        run: |  
          cd helm-chart-repo  
          gh pr create --base main --head $NEW_BRANCH --title "Update backend tag to ${{ steps.tag_version.outputs.new_tag }}" --body "This PR updates the backend image tag to version ${{ steps.tag_version.outputs.new_tag }}."  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      # - name: Deploy the Helm chart  
      #   run: |  
      #     cd helm-chart-repo  
      #     helm repo add my-repo <your-git-repo-url>  
      #     helm repo update  
      #     helm upgrade --install my-app my-repo/my-app --values values.yaml
