name: CI-PR

on:
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        id: build_image
        run: |
            docker build -t test/negar-backend:latest .
        #   docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/negar-backend:latest .
